```{r, warning = FALSE, message = FALSE, fig.align = "center"}
check_pkg <- function(x)
{
  if (!require(x,character.only = TRUE, quietly = TRUE))
  {
    install.packages(x,dep=TRUE)
    if(!require(x,character.only = TRUE, quietly = TRUE)) stop("Package not found")
  }
}

# Call check_pkg() to install/load the required packages
check_pkg("dplyr")
check_pkg("readr")
check_pkg("sf")
check_pkg("ggplot2")
check_pkg("ggpubr")
check_pkg("lubridate")
check_pkg("zoo")
check_pkg("tmap")
check_pkg("leaflet")
```

#Task 1
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#import the data
wildboar <- read_delim("data/wildschwein_BE_2056.csv", ",")
#convert dataset into sf object; use remove = FALSE to preserve original coordinates
wildboar <- st_as_sf(wildboar, coords = c("E", "N"), crs = 2056, remove = FALSE)
```

#Task 2
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#calculate time difference
wildboar <- wildboar %>%
  group_by(TierID) %>%
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")))
wildboar
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#How many individuals were tracked?

#show individuals with plot
ggplot(wildboar, aes(DatetimeUTC, TierName)) +
  geom_point()

cat(cat("There are", n_distinct(wildboar$TierName), "different individuals. The name of these individuals are: "), cat(for(n in 1:(length(unique(wildboar$TierName))-1))
  {cat(paste0(unique(wildboar$TierName)[n], ", "))}), cat(paste0(unique(wildboar$TierName)[length(unique(wildboar$TierName))], "."))) 
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#For how long were the individual tracked? Are there gaps?

ggplot(wildboar, aes(timelag/60)) +
  geom_histogram(binwidth = 1) +
  lims(x = c(0, 5000/60)) +
  scale_y_log10()
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#Were all individuals tracked concurrently or sequentially?

wildboar %>%
  ggplot(aes(DatetimeUTC, timelag, colour = TierName)) +
  geom_point() +
  geom_line()

print("The tracking for Sabi started earlier than for the other two but it also ended earlier. During a time period between November 2014 and March 2015 all three individuals were tracked concurrently.")
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#What is the temporal sampling interval between the locations?

wildboar %>%
  filter(DatetimeUTC < "2014-08-24") %>%
  ggplot(aes(DatetimeUTC, timelag, colour = TierName)) +
  geom_point() +
  geom_line()

print("The temporal sampling interval varies. During the night time the interval is shorter as wildboars are night active. During the day time there are fewer samplings as they are asleep.")
```

#Task 3
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#calculate the distance between to tracking positions
wildboar <- wildboar %>%
  group_by(TierName) %>%
  mutate(steplength = sqrt((E-lead(E))^2+(N-lead(N))^2))
#calculate average velocity
wildboar <- wildboar %>%
  group_by(TierName) %>%
  mutate(speed_ms = steplength/timelag)

print("The unit is m/s.")
```

#Task 4
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#import dataset caro60
caro <- read_delim("data/caro60.csv", ",")
#convert into sf object
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)
#calculate different granularities
seq_3 <- seq(from = 1, to = nrow(caro), by = 3)
caro_3 <- slice(caro, seq_3)
seq_6 <- seq(from = 1, to = nrow(caro), by = 6)
caro_6 <- slice(caro, seq_6)
seq_9 <- seq(from = 1, to = nrow(caro), by = 9)
caro_9 <- slice(caro, seq_9)
#calculate attributes for original
caro <- caro %>%
  group_by(TierID) %>%
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC), DatetimeUTC)),
         steplength = sqrt((E-lead(E))^2+(N-lead(N))^2),
         speed = steplength/timelag)
#calculate attributes for 3 interval
caro_3 <- caro_3 %>%
  group_by(TierID) %>%
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC), DatetimeUTC)),
         steplength = sqrt((E-lead(E))^2+(N-lead(N))^2),
         speed = steplength/timelag)
#calculate attributes for 6 interval
caro_6 <- caro_6 %>%
  group_by(TierID) %>%
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC), DatetimeUTC)),
         steplength = sqrt((E-lead(E))^2+(N-lead(N))^2),
         speed = steplength/timelag)
#calculate attributes for 9 interval
caro_9 <- caro_9 %>%
  group_by(TierID) %>%
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC), DatetimeUTC)),
         steplength = sqrt((E-lead(E))^2+(N-lead(N))^2),
         speed = steplength/timelag)
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#plot data
#plot original/ 3 minutes
ggplot() +
  geom_point(data=caro, aes(x=E, y=N, colour = "1 minute"), size = 2) +
  geom_path(data=caro, aes(x=E, y=N, colour = "1 minute"), linewidth = 0.8) +
  geom_point(data=caro_3, aes(x=E, y=N, colour = "3 minutes"), size = 2) +
  geom_path(data=caro_3, aes(x=E, y=N, colour = "3 minutes"), linewidth = 0.8) +
  scale_color_manual(name = "Trajectory", values = c("1 minute" = "blue", "3 minutes" = "red")) +
  ggtitle("Comparing original- with 3 minutes-resampled data")
#plot original/ 6 minutes
ggplot() +
  geom_point(data=caro, aes(x=E, y=N, colour = "1 minute"), size = 2) +
  geom_path(data=caro, aes(x=E, y=N, colour = "1 minute"), linewidth = 0.8) +
  geom_point(data=caro_6, aes(x=E, y=N, colour = "6 minutes"), size = 2) +
  geom_path(data=caro_6, aes(x=E, y=N, colour = "6 minutes"), linewidth = 0.8) +
  scale_color_manual(name = "Trajectory", values = c("1 minute" = "blue", "6 minutes" = "red")) +
  ggtitle("Comparing original- with 6 minutes-resampled data")
#plot original/ 9 minutes
ggplot() +
  geom_point(data=caro, aes(x=E, y=N, colour = "1 minute"), size = 2) +
  geom_path(data=caro, aes(x=E, y=N, colour = "1 minute"), linewidth = 0.8) +
  geom_point(data=caro_9, aes(x=E, y=N, colour = "9 minutes"), size = 2) +
  geom_path(data=caro_9, aes(x=E, y=N, colour = "9 minutes"), linewidth = 0.8) +
  scale_color_manual(name = "Trajectory", values = c("1 minute" = "blue", "9 minutes" = "red")) +
  ggtitle("Comparing original- with 9 minutes-resampled data")
#plot all sampling intervals
ggplot() +
  geom_line(data=caro, aes(x=DatetimeUTC, y=speed, colour = "1 minute"), linewidth = 0.7) +
  geom_line(data=caro_3, aes(x=DatetimeUTC, y=speed, colour = "3 minutes"), linewidth = 0.7) +
  geom_line(data=caro_6, aes(x=DatetimeUTC, y=speed, colour = "6 minutes"), linewidth = 0.7) +
  geom_line(data=caro_9, aes(x=DatetimeUTC, y=speed, colour = "9 minutes"), linewidth = 0.7) +
  scale_color_brewer(name = "Trajectory", palette = "Set2") +
  ggtitle("Comparing derived speed at different sampling intervals") +
  xlab("Time") +
  ylab("Speed [m/s]")

print("With increasing intervals the maximum speed decreases and the lines are smoothed.")
```

#Task 5
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#calculate rolling window 3
roll_3 <- caro %>%
  group_by(TierID) %>%
  mutate(roll_speed = rollmean(speed, k=3, fill= NA, align = "left")
)
#calculate rolling window 6
roll_6 <- caro %>%
  group_by(TierID) %>%
  mutate(roll_speed = rollmean(speed, k=6, fill= NA, align = "left")
)
#calculate rolling window 9
roll_9 <- caro %>%
  group_by(TierID) %>%
  mutate(roll_speed = rollmean(speed, k=9, fill= NA, align = "left")
)
#plot results
ggplot() +
  geom_line(data=roll_3, aes(x=DatetimeUTC, y=roll_speed, colour = "3"), linewidth = 0.7) +
  geom_line(data=roll_6, aes(x=DatetimeUTC, y=roll_speed, colour = "6"), linewidth = 0.7) +
  geom_line(data=roll_9, aes(x=DatetimeUTC, y=roll_speed, colour = "9"), linewidth = 0.7) +
  scale_color_brewer(name = "Window Size", palette = "Set2") +
  ggtitle("Comparing derived speed at different sampling intervals") +
  xlab("Time") +
  ylab("Speed [m/s]")
```

#Task 7
```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#import data
posmo <- read_delim("data/posmo_2023-04-05T00_00_00+02_00-2023-05-01T23_59_59+02_00.csv", ",")
#convert into sf object and transform to Swiss CRS
posmo <- st_as_sf(posmo, coords = c("lon_x", "lat_y"), crs = 4326, remove = FALSE, na.fail = FALSE) %>%
  st_transform(crs=2056)
#plot data
tmap_mode("view")
tm_shape(posmo) +
  tm_dots()
```