```{r, warning = FALSE, message = FALSE, fig.align = "center"}
check_pkg <- function(x)
  {
    if (!require(x,character.only = TRUE, quietly = TRUE))
    {
      install.packages(x,dep=TRUE)
        if(!require(x,character.only = TRUE, quietly = TRUE)) stop("Package not found")
    }
}

# Call check_pkg() to install/load the required packages
check_pkg("dplyr")
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#define time right now
now <- Sys.time()
#define time later
later <- now + 10000
#calculate time difference and change class to numeric
time_difference <- as.numeric(difftime(later, now, units = "mins"))
time_difference
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#using lead and lag
numbers <- 1:10
lead(numbers, n=2)
lag(numbers, default = 0)
```

```{r, warning = FALSE, message = FALSE, fig.align = "center"}
#load data
wildboar <- tibble(
  TierID = c(rep("Hans", 5), rep("Klara", 5)),
  DatetimeUTC = rep(as.POSIXct("2015-01-01 00:00:00", tz = "UTC") + 0:4 * 15 * 60, 2))
wildboar
#calculate timelag
wildboar$timelag <- as.numeric(difftime(lead(wildboar$DatetimeUTC), wildboar$DatetimeUTC))
wildboar$timelag
#calculate timelag only across same individuals
wildboar <- group_by(wildboar, TierID)
wildboar <- mutate(wildboar, timelag_true = as.numeric(difftime(lead(DatetimeUTC), DatetimeUTC)))
wildboar
```
